create a button on the login page
VertisanPRO/PterodactylRegister pull request #3
Opened 2022-07-08 09:27 UTC by v8j

2022-07-10 05:59 UTC, PadowYT2 requested changes

2022-07-10 05:59 UTC, PadowYT2 commented on Registration Module Files/resources/scripts/components/auth/LoginContainer.tsx
> +                            to={'/auth/register'}
Needs to refresh the page the page after clicking

2022-07-10 06:07 UTC, PadowYT2 commented on Registration Module Files/resources/scripts/components/auth/LoginContainer.tsx
> +                            to={'/auth/register'}
Try adding ```js
const reloadpage = document.getElementById('reloadpage')
button.onclick = () => {
  window.location.reload();
}``` and make put an id of `reloadpage` in the Link

2022-07-22 07:56 UTC, PadowYT2 commented
No response, closing

2022-07-22 07:56 UTC, closed without merging

2022-10-27 10:05 UTC, v8j commented
<__<